name: 🐞 Bug Report
description: File a bug/issue
title: "[BUG] <title>"
labels: ["bug"]
body:
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what the bug is.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. Go to '...'
      1. Click on '....'
      1. Scroll down to '....'
      1. See error
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else? 
    description: |
      Screenshots? Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment and Versions
    description: |
      examples:
        - **Frappe Version**: v14.6.9
        - **ERPNext Version**: v14.6.9
        - **Custom App Version**: v0.6.2
    value: |
        - Frappe Version: 
        - ERPNext Version: 
        - Custom App Version: 
    render: markdown
  validations:
    required: false
- type: dropdown
  id: version
  attributes:
    label: Operating System
    description: On what OS are you seeing the problem on?
    multiple: true
    options:
      - Windows
      - MacOS
      - Android
      - iOS
      - Other
  validations:
    required: true
- type: dropdown
  id: browsers
  attributes:
    label: What browsers are you seeing the problem on?
    multiple: true
    options:
      - Chrome
      - Microsoft Edge
      - Firefox
      - Safari
      - Other
